version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-build steps (if any)..."

  build:
    commands:
      - echo "Building Flask application (if any)..."

  post_build:
    commands:
      - echo "Post-build steps (if any)..."

