branch-defaults:
  main:
    environment: game-results-app-env
environment-defaults:
  game-results-app-env:
    branch: null
    repository: null
global:
  application_name: game-results-app
  default_ec2_keyname: aws-eb2
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
